### ISSUE TITLE
p values for DMR scores?

### ISSUE THREAD

**Issue by EpiAllele** [nanoporetech/modkit#122]
Hello ModKit Devs. Does the score produced using the “modkit dmr” command come with an associated p-value? If not, do you have instructions on how to do this? Or perhaps refer a third party tool that can do differential methylation analysis with significance testing using modkit bedmethyl output? Thanks

**Comment by EpiAllele** [comment]
Hi @ArtRand . Thanks for the quick response. The experiment is a simple setup of comparing a treatment (3 biological replicates) vs control (3 biological replicates) and looking at effects of the treatment on changes in methylation. I have very limited computational background but I will take a look at the polars code from issue 83 and also read up on discussions from issue 93.

**Comment by ArtRand** [comment]
Hello @EpiAllele, 

If you suspect that the treatment is going to have an effect at certain regions, I would use those regions as input to `modkit dmr multi` on all 6 of the samples. There is documentation on how to use [multiple samples](https://nanoporetech.github.io/modkit/intro_dmr.html#running-multiple-samples). Then I would take the high scoring regions and look at the reads in a viewer such as IGV. Honestly, I find this is the simplest first step to get an idea of what's happening in an experiment. If you don't have a set of regions you want to look at, you can run `modkit dmr` without the regions and it will score all of the individual sites. Then you can look and see if the consistently high scoring sites are in interesting areas of the genome. The algorithm with individual sites is a little slower than I'd like right now - but I'm going to have a faster version in the next release. Good luck!

**Comment by EpiAllele** [comment]
Thanks @ArtRand ! This is really helpful. For viewing in IGV, is it as simple as loading the indexed modbam and checking the modified bases option on the bam track?

**Comment by ArtRand** [comment]
@EpiAllele It's just that simple! I like to also add a bedgraph track from modkit.

**Comment by lucy924** [comment]
Hello @ArtRand and @EpiAllele - I'm looking for some advice.
I've been using `dmr multi` on version 0.2.8 with the regions as CpG Islands. This does not output the MAP-based p-value, as I understand it because this is on regions not single sites. I'm not a statistician - I have briefly looked at issue 93 and will delve more into that shortly, but I was wondering if you had any advice on finding significance of the score values using the regions option? 
My experiment setup is the same as @EpiAllele mentioned here. Most of my scores are <20 but in a single paired test I have a few between 20 and 40, one at 68 and one at 282. The other pairs have a similar type of spread, although not with any higher than 100.
I appreciate the great package! Thank you!
