### ISSUE TITLE
Per-read support?

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/modkit#17]
Hi,
Thanks for the new tool! I am assuming that the bedMethyl output is the "aggregated" site result from the read level currently. So any chance that you will add the per-read level support? It might be interesting to explore the read heterogeneity at the single-base, single-read level.

**Comment by ArtRand** [comment]
Hello @PanZiwei,

This exact functionality is coming in the next release, which should _hopefully_ be this week!

**Comment by PanZiwei** [comment]
Looking forward to the new feature!

I have 2 quick questions about pileup also: 
1) Since the modification is predicted independently, what if the site is CpG on the reference genome, but the base is not CpG in the base-called sequence in the bam file? How do you deal with the specific case when introducing a reference sequence? 

2) In modbam2bed you have the design for --canon_threshold and --mod_threshold. 
So the logic is: a) if meth_prob < canon_threshold - unmethlated b) meth_prob > mod_threshold - methylated c) canon_threshold <= meth_prob <= mod_threshold - ambigious. 
Do you have a similar design in the modkit? If so, how do you deal with the ambiguous situation above? How do you distinguish the ambiguous situation with the 1) case (the site is not predicted on the read)?

Thank you!

**Comment by ArtRand** [comment]
@PanZiwei thanks for the good questions. I'll try and add some detail this to the docs. 

> Since the modification is predicted independently, what if the site is CpG ONLY on the reference genome, but the base is not CpG in the base-called sequence in the bam file? For example, the site is CG on the reference genome but is AG on the read. How do you deal with the specific case when introducing a reference sequence?

If the read sequence does not contain a CpG then the CG-model will not make a prediction and the base modification call won't end up in the pileup. In your example where there is a CG->AG error, there won't be a call because there is no cytosine and the read will be counted in N_diff. There could also be a CG->CW error, in this case the CG model won't make a call because it requires a CG motif, in this case the read will be counted in N_nocall. We are in the process of releasing "all-context" cytosine models that _will_ make a call at a CG->CW error. If the read doesn't contain a cytosine mapped at the reference position there will be no methylation call (will be tabulated in N_diff in modkit).

> In modbam2bed you have the design for --canon_threshold and --mod_threshold.
So the logic is: a) if meth_prob < canon_threshold - unmethlated b) meth_prob > mod_threshold - methylated c) canon_threshold <= meth_prob <= mod_threshold - ambigious.
Do you have a similar design in the modkit? 

Yes. The recommended method is to let modkit estimate the threshold from your data on the fly. But you can also explore the output distributions with `sample-probs`. When you set `--filter-threshold 0.9` what you're enforcing is 

```
p_5mC: 0.95 p_C: 0.05 => 5mC
p_5mC: 0.05 p_C: 0.95 => C
p_5mC: 0.70 p_C: 0.30 => Fail

```
A `Fail` call will not be added to the valid coverage, the canonical calls, or the methylated calls, it will be added to N_fail (see [definitions](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#definitions)). There is more discussion at [Issue 15](https://github.com/nanoporetech/modkit/issues/15). This seems to be a point of confusion, so the docs are being improved in this area.

> If so, how do you deal with the ambiguous situation above? 

If the call fails to be above the threshold, it's marked as Fail and not used.

> How do you distinguish the ambiguous situation with the 1) case (the site is not predicted on the read)?

If the site is not basecalled as a C, there will be C-modification call at all and it will be counted towards N_diff.

**Comment by PanZiwei** [comment]
Thanks for the detailed answer! So maybe to simplify, there are 2 categories for NA: one is relevant to the model itself (Ndiff, Nnocall), and one is relevant to the customer setting(Nfail).
As you mentioned, there are indeed many different exceptions and it is not an easy task to handle the cases. Really appreciate the effort.

**Comment by PanZiwei** [comment]
Hi, any idea about the estimated release time for the per-read support? Thanks!

**Comment by ArtRand** [comment]
> Does the mapped per-read table only consider primary alignment for modkit extract?
I noticed that primary alignment are only used when Constructing bedMethyl tables for the per-site table, but not sure about per-read.

Only the primary alignment is used, due to how the MM tag works, it's challenging to get the modification positions for non-primary alignments. I'd be curious to know if you have a use case for using non-primary alignments.

> Why there is ref_position=-1 in the per-read result? Does it mean that the reads are not mapped to the reference genome? (They indeed disappear when I added --mapped-only)

Correct, as per the [documentation](https://nanoporetech.github.io/modkit/intro_extract.html#description-of-output-table), `ref_position` value of `-1` means that base in the read is not mapped to the reference, for example an insert or soft-clipped base.
