### ISSUE TITLE
how to allele-specific methylation calling?

### ISSUE THREAD

**Issue by sahuno** [nanoporetech/modkit#185]
Hi,
may i inquire how to do allele specific/happlotype resolved methylation calling and analysis? a look in the literature requires phasing tools like whatsapp etc...
i already did base calling 5mc_5hmC dorado then methylation calling with modkit. 

thanks in advance
-S

**Comment by ArtRand** [comment]
Hello @sahuno, 

In order to perform haplotype-specific methylation analysis, you'll need to use a phasing tool like [whatshap](https://whatshap.readthedocs.io/en/latest/) first. The output of this tool should be "haplotagged" reads where each phased read has a `HP` tag usually `HP:1` and `HP:2` indicating the two haplotypes. Then you can use `modkit pileup --partition-tag HP` and you'll get a pileup for `HP:1` and `HP:2` separately. Then you can use the [differential methylation](https://nanoporetech.github.io/modkit/intro_dmr.html) command to sites that are different (i.e. haplotype specific).

**Comment by sahuno** [comment]
thanks!
