### ISSUE TITLE
How to generate hydroxymethylation in pileup?

### ISSUE THREAD

**Issue by weishwu** [nanoporetech/modkit#206]
The ONT reads were basecalled using Dorada with the model `dna_r10.4.1_e8.2_400bps_sup@v4.3.0_5mCG_5hmCG@v1`. I tried using modkit to generate CpG methylation and hydroxymethylation pileups. It turned out that the results have similar methylation levels on most CpGs. I wonder if I'm using modkit correctly.

```
# for methylation
modkit pileup --cpg --ref hg38.fa --ignore h --combine-strands sample.bam sample.CpG_m.bed

# for hydroxy methylation
modkit pileup --cpg --ref hg38.fa --ignore m --combine-strands sample.bam sample.CpG_hm.bed
```

**Comment by ArtRand** [comment]
@weishwu 
I think the confusion is that `--ignore` actually [changes the probabilities](https://nanoporetech.github.io/modkit/collapse.html#removing-dna-base-modification-probabilities) it doesn't omit the bedmethyl records. If you're trying to get a 5hmC-only pileup, you can pipe the output through `awk` like this:

```bash
$ modkit pileup --cpg --ref hg38.fa --combine-strands sample.bam - | awk '$4=="h"' > sample.CpG_h.bed
```

In this case you don't need to keep the original file because the number of 5mC reads will be [column 14](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#definitions), N_other_mod.

Does this answer your question?

**Comment by weishwu** [comment]
@ArtRand 
Thanks! I'll try that. Does this mean I cannot use `--ignore h` either for non-hydroxy 5mC? For 5mC I will have to do:
```
$ modkit pileup --cpg --ref hg38.fa --combine-strands sample.bam - | awk '$4=="m"' > sample.CpG_h.bed
```
Is this correct?

**Comment by ArtRand** [comment]
@weishwu, 

That's correct. Alternatively you could use this awk command to convert the `sample.CpG_h.bed` into `sample.CpG_m.bed` and avoid running the computation again.

awk -v OFMT="%.2f" -v OFS="\t" '{print $1, $2, $3, "m", $5, $6, $7, $8, $9, $10, (($14 / $10) * 100), $14, $13, $12, $15, $16, $17, $18}'

The `--ignore` option is meant to indicate that even though you have base modification predictions for a specific state (say 5hmC), you want to ignore that possibility. It is intended to simulate what a 2-mode (or n minus 1 mode) caller would do.

**Comment by ArtRand** [comment]
Hello @weishwu, 

I'm going to take on the second part of your question first, since I think it's more important to your analysis. The `h` and `m` rows in the `modkit extract` are not independent, they are the two probabilities output by the model, so concretely

$$
p_{\text{h}} = \text{probability of 5hmC}
$$

$$
p_{\text{m}} = \text{probability of 5mC} 
$$

$$
p_{\text{canonical}} = \text{probability of unmodified} = 1 - p_{\text{m}} - p_{\text{h}}
$$

To be perfectly honest, I'm not familiar enough with how NanoMethPhase uses the probabilities, but I imagine you don't want to use the 5mC and 5hmC probabilities separately. What I would do is use `modkit extract` like this:

```bash
$ modkit extract ${mod_bam} null --read-calls ${read_calls_tsv}
```

The `${read_calls_tsv}` will contain a `call_prob` column ([schema](https://nanoporetech.github.io/modkit/intro_extract.html#tabulating-base-modification-calls-for-each-read-position)) that I bet is more suitable. 

As for the first part. I agree that there is a lot of nuance to how the probabilities are used and how they become counts in `pileup` (and `--read-calls`), that's why I've tried to write as much approachable [documentation](https://nanoporetech.github.io/modkit/collapse.html) of the specifics as possible. I hope that as multi-class modifications (5hmC/5mC, 4mC/5mC) become more common `--ignore` will become obsolete.

**Comment by weishwu** [comment]
Hi @ArtRand 
I do want to measure 5mC and 5hmC separately. Do you mean that the `mod_qual ` in the `modkit extract` default output actually contains both 5mC and 5hmC, but the `call_prob` column in the output if using `--read-calls` is for `h` and `m` separately?
Sorry I'm confused about how the `--read-calls` output is different from the default output.

My current command-line is:
```
modit extract --include-bed {params.roi_core} --cpg --mapped-only --threads {threads} --reference {params.genome_fasta} {input.bam} {modkit_extract.csv}

# extract read and mod_qual for NanoMethPhase
echo -e "chrom\tpos\tstrand\tpos_in_strand\treadname\tread_strand\tprob_0\tprob_1\tcalled_label\tk_mer" >{input}.reformatted.tsv
awk '{{OFS="\t";if (($12=="m")) {{print $4,$3,$6,"NA",$1,"NA",1-$11,$11,"NA",$14}}}}' {modkit_extract.csv} >> {modkit_extract}.reformatted.tsv

python /usr/share/NanoMethPhase/nanomethphase.py methyl_call_processor --tool_and_callthresh deepsignal:0.6 -mc {modkit_extract}.reformatted.tsv -t {threads} | sort -k1,1 -k2,2n -k3,3n | bgzip > {output.bedgz}
```

**Comment by ArtRand** [comment]
Hello @weishwu 

> I do want to measure 5mC and 5hmC separately. Do you mean that the mod_qual in the modkit extract default output actually contains both 5mC and 5hmC, but the call_prob column in the output if using --read-calls is for h and m separately? Sorry I'm confused about how the --read-calls output is different from the default output.

The `mod_qual` in the extract default output is the probability of 5hmC and 5mC but these are not independent measurements (see the [above comment](https://github.com/nanoporetech/modkit/issues/206#issuecomment-2168779716)). A base in a read will have a probability of being canonical, 5mC, and 5hmC, but in general we assume that the base has one of these chemical structures. The [read calls output](https://nanoporetech.github.io/modkit/intro_extract.html#tabulating-base-modification-calls-for-each-read-position) takes these probabilities, applies the same pass/fail criteria as in `pileup` and produces a single "call" for the most likely predicted state of the base, the `call_prob` is then the probability of that state. 

From a quick read of the [docs](https://github.com/vahidAK/NanoMethPhase/blob/master/README.md#methyl_call_processor) I would use the read-calls directly and skip the `methyl_call_processor` step.

It doesn't appear that nanomethphase handles multiple modifications (maybe I'm wrong), so you may need to either separate the rows in the read-calls table based on their `call_code` or use the `--ignore h` option so that you get 2-class 5mC/canonical calls. 

Sorry that getting these tools to work together isn't more straight forward. 

It doesn't look like NanoMethPhase actually uses the methylation information while phasing (it offloads that task to WhatsHap which uses the primary sequences of the reads and SNVs). You could run `modkit pileup --partition-tag HP` to get the pileup separated by haplotype. Then use `modkit dmr [--segment]` to find differentially methylated regions and bases (there is some code in the [docs](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#partitioning-reads-based-on-sam-tag-values)).

**Comment by weishwu** [comment]
@ArtRand 
Thanks for the detailed explanation!
I'll use `call_prob` and try `modkit dmr [--segment]`.

**Comment by weishwu** [comment]
Hi @ArtRand 
Sorry to reopen this. My ONT run is AS so I want to limit the analysis on ROIs. Can I run `modkit extract` as below instead of using `null` to generate the read calls?

```
modkit extract \
  --include-bed {params.roi_core} \
  --cpg \
  --mapped-only \
  --threads {threads} \
  --reference {params.genome_fasta} \
  --read-calls {output.readcalls}
  {input.bam} {modkit_extract.csv}
```

**Comment by eesiribloom** [comment]
@weishwu I am also interested in looking at phasing the output of modkit and looking at 5hmCG and 5mCG separately (it looks like we have evidence of allele-specific 5hmC). 

What did you find was the best approach? 

how do you navigate regions of allele-specific or hemimethylation when it comes to applying thresholds/filters with `modkit pileup` (Im assuming a hemi-methylated region would have probability 0.5 which is likely below the default threshold calcluated by modkit)
