### ISSUE TITLE
Turning off --cpg Modkit argument via wf-human-variation

### ISSUE THREAD

**Issue by hassebossenbroek** [nanoporetech/modkit#221]
Hi,

Sorry for cross-posting - I wasn't fully sure which forum this should go into, so I've also asked on the wf-human-variation Github page. Feel free to delete if not appropriate. 

I have some bam files with modified base calls in any genomic context (5mC and 5hmC as opposed to 5mCG and 5hmCG). To analyse these, I'm trying to use the wf-human-variation, but I want to turn off the --cpg argument that gets passed to Modkit by default. I know that I can use --modkit_args to specify arguments to modkit, but it's not entirely clear to me how this works. The modkit pileup documentation seems to suggest --cpg is not a TRUE/FALSE argument, suggesting I can't just use --modkit_args --cpg FALSE. So my question is: If I pass --combine-strands as the only argument to --modkit_args, will the pipeline assume that the --cpg argument is no longer there and therefore look at the whole genome?
Many thanks!

**Comment by ArtRand** [comment]
Hello @hassebossenbroek, 

Passing `--combine-strands` won't do what you want. One workaround is to use pass `--motif CH 0` you will get all CG and CH positions (effectively all C-positions). The output wont be exactly the same as if you removed the `--cpg` flag, however, because it will not include positions where >= 1 read had a base modification call but the reference was not C. Keep in mind that using this option will likely increase the disc and memory usage of the modkit step in the workflow. Also note that with this option you _cannot_ use `--combine-strands` (modkit will error when you do).

**Comment by hassebossenbroek** [comment]
Hi Arthur,

Thank you very much for your reply, that was very helpful.
Can I just check that I've understood you correctly - you say "positions where at least one read had a base modification call but the reference was not C". Would that be mostly positions where there is a mutation, which means there is now a methylatable C that is absent in the human reference genome? My cells of interest are a cancer cell line, so if I've understood this correctly it seems like I might potentially miss a fair few positions with this approach. Maybe I'm better off just running modkit pileup outside of the wf-human-variation. 

Thank you,
Best wishes,
Hasse
