### ISSUE TITLE
Error when running  tabix -p bed pileup.bed.gz

### ISSUE THREAD

**Issue by yinyuanmtu** [nanoporetech/modkit#236]
[E::get_intv] Failed to parse TBX_GENERIC: was wrong -p [type] used?
The offending line was: "chrom  chromStart      chromEnd        name    score s                                                                                                              trand   thickStart      thickEnd        color   valid_coverage  percent_modifie                                                                                                              d       count_modified  count_canonical count_other_mode        count_delete  c                                                                                                              ount_fail       count_diff      count_nocall"

mod_kit 0.3.1
tabix (htslib) 1.20-54-gfbe5ff6c

**Comment by ArtRand** [comment]
Hello @yinyuanmtu, 

Did you run `modkit pileup` with the `--with-header` flag? I suppose that modkit should put the `#` comment character in front of the header so that the associated tools know to ignore it. (I personally don't like having my first header name be `#chrom` when I parse the table into polars or similar). I can fix that in the next release. Here's a work-around in the mean time.

1. Push the table through `awk`:
```bash
$ awk 'NR>1' ${pileup_bed} | bgzip > ${pileup_bgzip}
$ tabix -p bed ${pileup_bgzip}
```

**Comment by yinyuanmtu** [comment]
Thanks Arthur for the quick help!
