### ISSUE TITLE
Calling methylation at new CpG sites 

### ISSUE THREAD

**Issue by sumudu-rangika** [nanoporetech/modkit#302]
Hi Arthur,

Thank you for this nice tool!! 

I used modkit to call 5mC methylation at reference CpG sites! The command I used is below. (version mod_kit 0.3.2)
`modkit pileup <input.bam> <out.bed> --cpg --ref $ref --ignore h --combine-strands --partition-tag HP --prefix bam1_hp --threads 10`

 I have few questions and greatly appreciate your input. 

1) My study looks at 5mC methylation levels at CpG sites within a gene promoter to understand contribution of methylation to drug response variability among individuals. Within the cohort some subjects carry a SNP (for example A>G mutation), which creates a new CpG site. I initially called 5mC methylation using a reference. Now I want to get the methylation level at this new CpG site. 

I saw an answer you provided on a similar matter  _"If you want the positions that were CpG in the read but not CpG in the reference (reference CH), you can use dorado with the CpG modification model and then use_ `_$ modkit pileup ${mod_bam} ${pileup_ch_bedmethyl} --motif CH 0 --ref ${ref}_`

What does reference CH means? During methylation aware basecalling are the new CpG sites are also included or does it consider only reference CpG sites? 

I tried with my BAM file without using the reference. But I got an error asking to include a reference. This is the command I used.

`modkit pileup phased.bam sample1.bed --ignore h --combine-strands --partition-tag HP --prefix sample1_hp --threads 10  --include-bed /cyp2d6_promoter_cpg.bed --motif CG 0`

2) In long reads, what exactly --combine-strands means? same read that pass through the pore in different directions and not refereing to haplotype 1 and 2, am I correct? I'm interested in looking at allele-specific methylation levels for my subjects. 

Thank you
Best Regards
Sumudu

**Comment by ArtRand** [comment]
Hello @sumudu-rangika, 

> What does reference CH means?

A reference CH means cytosine followed by {A, C, T} (i.e. not a G). 

During methylation aware basecalling are the new CpG sites are also included or does it consider only reference CpG sites?

If you use the CpG base modification model, for a given read, it will produce a base modification call at every CpG _in the read_. Now if this read aligns to a CA in the reference genome (due to a G>A transition) you will not see this position in the bedMethyl when using the `--cpg` flag since it's not a CpG in the reference. You can use `--motif CH 0` to produce a bedMethyl file for these positions, which if you've run the CpG _modification model_ will be only positions where there was a CpG in the read, but not in the reference. It's a bit of an odd trick, but it could get to the question you're trying to answer. An alternative way to do this would be using the tables from `modkit extract calls`, and use the `ref_kmer` column, but I think this method running `pileup` twice will be easier. 

> In long reads, what exactly --combine-strands means?

This means you combine the modification counts on the (+)-strand and (-)-strand. Please find the documentation [here](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#narrowing-output-to-cpg-dinucleotides). 

> same read that pass through the pore in different directions and not refereing to haplotype 1 and 2, am I correct? 

No, only one strand of DNA is read at a time, all this means is you taken the base modification counts on the (-)-strand `G` and sum it with the (+)-strand `C`. 

> I'm interested in looking at allele-specific methylation levels for my subjects.


You're command looks OK to me, you may want to try `modkit dmr pair` to find regions with differential methylation, find the documentation [here](https://nanoporetech.github.io/modkit/intro_dmr.html).

**Comment by sumudu-rangika** [comment]
Many Thanks Arthur for replying to my queries. 

Just another point to clarify. I used --partition-tag HP --prefix bam1_hp in my command and got 3 set of files.

bedmethyl file for haplotype 1, bedmethyl file for haplotype 2 and a bedmethyl file for undefined reads. If i use a BAM without phasing it crated one bedmethyl file. My question is that, whether it would be more reasonable to use the file created without considering phasing if I'm only focusing on per site methylation ? Or would it be accurate if I just sum up methylation at each CpG site across all 3 files? (e.g 100% + 80% + 70%) and average to get a per site methylation level? 

In my initially analysis I filtered each bedmethyl file for haplotype 1 and bedmethyl file for haplotype 2 to only retain CpG sites that support by at least 5 reads. However, I now realize this might not be a not good approach because when considering both files together the actual no of reads that support the CpG site is >5. And in this I did not consider the undefined file, which also has reads that support the CpG methylation even though the reads were not assigned a phase. 

So, a good way might be to sum up and average the methylation at each CpG site in all 3 files or create one file excluding --partition-tag HP. Greatly appreciate you input to clear my doubts. 

Thank you very much.
Best
Sumudu

**Comment by ArtRand** [comment]
Hello @sumudu-rangika, 

If you're not trying to separate the methylation counts by phase, I would not use `--partition-tag HP`. If you partition your reads on phase, you'll reduce the coverage since some reads will be HP1, some will be HP2, and some will have no phasing information. So you'll have <=50% of the coverage in each table.

You cannot take the average the way you've described, you'd have to sum the counts of modified and unmodified reads for each position, for each modification type. The next version of Modkit will have a function to merge bedmethyl tables.

**Comment by sumudu-rangika** [comment]
Thank you very much for clarifying this. Greatly appreciated! 

Best,
Sumudu

**Comment by ArtRand** [comment]
Great, happy to help.

**Comment by sumudu-rangika** [comment]
Hi Arthur,

Apologies for this very long query again, but I need to reopen this as I have now come across another question. 

I ran modkit without the `--parttition-tag HP` and got 5mC methylation data for CpGs within the promoter of my gene of interest. 

I'm investigating a cohort genotypically categorised under the same phenotype/trait. However, there is variability within the cohort that isn't captured genetically. I'm exploring whether methylation contributes to this observed variability. 

I have identified some individuals with one/more SNPs that either disrupt a reference CpG site or create a new CpG site within the promoter. For example for a C>T SNP which disrupt a reference CpG site, I want to see methylation differences at this site between CC (homo reference) and  CT (heterozygotes) within the cohort. In the case of TTs both haplotypes are zero. 

Previously, I averaged HP1 and HP2 methylation per site for CCs and CTs, to get a comparison figure. As averages were said to be incorrect, Then, I looked at without `--parttition-tag HP` data. Now I see some CC individuals have ~80% methylation at this site. Also some CTs have ~80% at this site while only one haplotype methylated and other has no methylation (I have attached a part of cohort for one such CpG site). Because, in case of CT it considers only filter passed modified and canonical base. Ndiff reads are high in this case with the C>T mutation but not counted in arriving at this methylation state. Overall, I feel that the methylation is over estimated here compared to CC where in CTs half of the reads are methylated and other half having the SNP. 

My cohort has samples from different populations. My next step would be to see if CCs and CTs have any ethnic-specific methylation differences. 

I am confused how to approach this. Should I recalculate methylation level at each position as 
(Nmod = Nmod + Ncanonical + Ndiff + Nnocall), so that all reads are captured in calculating the methylation? Does modkit dmr accounts for reads with a mutation when comparing methylation? 

Another thing I don't understand is Nnocall. The document explains this as the no of reads with a canonical base at the site but could be unmethylated due to CG>CH. But I don't see such changes while visualising in IGV. But I see high no of reads for Nnocall for CT individuals (I have attached a bedmethyl for one individual; highlighted are the positions with mutation where the inidvidual is heterozygous)

[42131469_new.xlsx](https://github.com/user-attachments/files/18030069/42131469_new.xlsx)
[example_sample.xlsx](https://github.com/user-attachments/files/18030073/example_sample.xlsx)

Let me know if you need a IGV image. 

Thank you very much.
Best,
Sumudu
