### ISSUE TITLE
Using Dorado+modkit for m6A analysis

### ISSUE THREAD

**Issue by baibhav-bioinfo** [nanoporetech/modkit#314]
Hello, 
I am using DRS data for m6A analysis using Dorado (basecall +methylation call)+ modkit (bam to bed and DMR analysis).

I have few queries which if cleared i would be much thankful.
(1) i wanted to know if 
dorado basecaller   rna004_130bps_hac@v5.1.0   /path/to/pod5
--modified-bases-models rna004_130bps_hac@v5.1.0_m6A_DRACH@v1/    --device cude:all --reference ref.fasta > calls.bam

this is correct approach for alignment along with basecalling.

also as other tools (eg. m6Anet) uses transcriptome rather than genome. which one would be more suitable to align with?.

(2) The resultant bed file (after modkit pileup) contains position with Nmod=0. Why are those in the output when my argument is to detect the m6A mod sites? do i need to filter out those, keeping only Nmod>=1?
also the file have Nother_mod column, what are those and why are we getting other mods
is there any option to get only relevant Nmod rows, in my case A? 

(3) For DMR analysis i wonder if the following is accurate for my case having 3 replicates for 2 conditions
modkit dmr pair \
  -a ${Control_1}.gz \
  -a ${Control_2}.gz \
  -a ${Control_3}.gz \
  -b ${Stress_1}.gz \
  -b ${Stress_2}.gz \
  -b ${Stress_3}.gz \
  -o ${dmr_result_replicates} \
  --ref ${ref} \
  --base A \
  --threads ${threads} \
  --log-filepath dmr.log

**Comment by ArtRand** [comment]
Hello @baibhav-bioinfo,

> (1) i wanted to know if `dorado basecaller rna004_130bps_hac@v5.1.0 /path/to/pod5 --modified-bases-models rna004_130bps_hac@v5.1.0_m6A_DRACH@v1/ --device cude:all --reference ref.fasta > calls.bam`  this is correct approach for alignment along with basecalling?

Yes this looks correct.

> also as other tools (eg. m6Anet) uses transcriptome rather than genome. which one would be more suitable to align with?

It depends on what you're trying to do. I would recommend reviewing the [minimap docs](https://github.com/lh3/minimap2?tab=readme-ov-file#map-long-mrnacdna-reads) to find the best settings for mapping to genome or the transcriptome. I would use `dorado aligner` and pass these settings via `--mm2-opts` so that the base modification information will be carried along with the reads.

> (2) The resultant bed file (after modkit pileup) contains position with Nmod=0. Why are those in the output when my argument is to detect the m6A mod sites? do i need to filter out those, keeping only Nmod>=1? also the file have Nother_mod column, what are those and why are we getting other mods is there any option to get only relevant Nmod rows, in my case A?

You can find a description of the bedMethyl schema [in the documentation](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#description-of-bedmethyl-output). To your question regarding `Nother_mod`, if you were using a model that makes predictions on multiple modification states (e.g. `rna004_130bps_hac@v5.1.0_inosine_m6A@v1`) you may see counts in this column.

> (3) For DMR analysis i wonder if the following is accurate for my case having 3 replicates for 2 conditions
```bash
  modkit dmr pair
  -a ${Control_1}.gz
  -a ${Control_2}.gz
  -a ${Control_3}.gz
  -b ${Stress_1}.gz
  -b ${Stress_2}.gz
  -b ${Stress_3}.gz
  -o ${dmr_result_replicates}
  --ref ${ref}
  --base A
  --threads ${threads}
  --log-filepath dmr.log
```

Yes this looks like a valid command to me.

**Comment by baibhav-bioinfo** [comment]
Thanks @ArtRand for the valuable responses.
I am clear on all issues except for the one with presence of Nother_mod in the file, because i ran the command with only m6A_DRACH model.

**Comment by baibhav-bioinfo** [comment]
hi @ArtRand 
I was able to run the DMR for my 2 conditions with 3 replicates each.
But as i can see, the table contains no such row (site) which have 0 modification in one condition and something in other. The table have rows (sites) which have at least 1 modification in one of the condition.

I mean there should be some sites which is only modified in one of the two condition and those should be interesting to study.
