### ISSUE TITLE
Error! zero reads in bam index

### ISSUE THREAD

**Issue by rainwala** [nanoporetech/modkit#32]
Hello, when I try the modkit pileup command using bam output from dorado basecaller modified_bases as input to modkit, it fails with the following errors:
```
modkit pileup -r /data/Homo_sapiens.GRCh38.106_no_alt_chrs.fa -t 150 dorado_0-3-0_dna_r10.4.1_e8.2_400bps_hac_v4.1.0_mod_bases.bam dorado_0-3-0_dna_r10.4.1_e8.2_400bps_hac_v4.1.0_mod_bases.bed
> attempting to sample 10042 reads from BAM
> Error! zero reads in bam index
```

The bam file was sorted and indexed using samtools. What am I doing wrong?

**Comment by rainwala** [comment]
The dorado basecalling command that produced the bam file was: 
`dorado basecaller /home/prom/dorado-0.3.0-linux-x64/models/dna_r10.4.1_e8.2_400bps_hac@v4.1.0 pod5_all/ --modified-bases 5mCG_5hmCG`

**Comment by ArtRand** [comment]
Hello @rainwala 

What's likely happening is that all of your reads are unmapped. Could you try `samtools idxstats dorado_0-3-0_dna_r10.4.1_e8.2_400bps_hac_v4.1.0_mod_bases.bam`? By default, `pileup` only used mapped bases for estimating the pass threshold, if it fails to find any you'll see this error. You could confirm by passing the `--include-unmapped` flag. However, you won't get a meaningful pileup (should see `Done, processed 0 rows.`) because with zero mapped reads, there aren't any to count! You can refer to the [dorado documentation](https://github.com/nanoporetech/dorado/#alignment) for how to perform alignment. Let me know if this helps.

**Comment by rainwala** [comment]
Thanks @ArtRand , that makes sense. I'll try mapping using dorado to the same reference I want to use with modkit, and see if that makes a difference and report back here.

**Comment by rainwala** [comment]
Thanks, that fixed the issue!
