### ISSUE TITLE
ImplicitProbModified

### ISSUE THREAD

**Issue by cherlynty** [nanoporetech/modkit#38]
Hi,

I am having similar issues with an empty bedfile, and have explored the closed issues.

I am working on Adaptive Sampling from GridIon and used guppy for basecalling and alignment.

`guppy_basecaller \ -i ${input_fast5s} -s ${output_folder} \ -c res_dna_r941_min_modbases_5mC_5hmC_v001.cfg \ --align_ref ${reference_fasta} \ --compress_fastq --bam_out --recursive`

and have checked that they are mapped from bamfiles and samtools idxstats. However, the bed files were empty, and I received an error

`[src/pileup/subcommand.rs::632][2023-07-12 22:30:19][INFO] Done, processed 0 rows. Processed ~0 reads and skipped ~3901 reads.`
`[src/read_cache.rs::372][2023-07-12 22:30:19][DEBUG] read bbe24401-4164-4742-a27a-bb2e121ca5a9, Skipped: record bbe24401-4164-4742-a27a-bb2e121ca5a9 has un-allowed mode (ImplicitProbModified), use '--force-allow-implicit' or 'modkit update-tags --mode ambiguous'`

bam eg:

> 3e2975b6-36df-4d6e-95fa-679aa0ea5111	16	chr1	2371141	60	86M9I29M1D54M2D42M1D13M3I98M1I25M2D22M3D18M1D10M1I30M8D17M25S	*	0	483	GGAGCTTGCAGTGAGCCAAGATCGTGCCACCGCACTCCAGCCTGGGTGACACAGCGAGACTCTGTCTCCAAACAACAACAACAACCACAACCACAACAACAACAACAACACCATGAAGAAAGATTCCTGGGTTTCAGTGATCCTCGCACCTCAGCCTCCCGAAGTGCTGGGATTTTAGGTGAGCCACTGTGCCTGACTGATAGTCTAATTTTAAAAAAATAAAACAATATTTGGGTAATAGACATTTCTCCAAAGAAGATAAACAAACAGCCAATCAACACAGCGAGAGCCACTCATCGTCATCACTCGTTAGGGAAATGCGAATCAAAATCACTGAGGAACTATCACTTCACACCCACAGCAGCTATTACAAAAAGACACACCAAGTGTTGGGAAGACGAGAGAAATCTGGAACCTTCATGCATTACTGGTGGGACTGCACAGCAATTTTGGAAAAAGCAATAATGTAACTGAAACGAAGTG	&,7,'(/.*.),)*,/$.)5&(%*%'))&,(*/+(%*2,+/-$,;),-*5/4+(,7=44*6891.962-9>;'01&&**/4(59.9(25808(,0,+3%,'1)4')*6'&.)0).-;<,<66'313<6):4&-&$((.,3+5*%(()&7:-=1(47*5:/5>;=:7++6B:'-71*%%&(,6:+<)06,*)+?5.+*5+<96-*<-,21;3,)9;;:0&*.11)#.&)/0.)%$##1&$)(6178;*0-<+/;61,=,40-84)==0-91(2.+.+18(5+:*.65,,*2=+'))%'*5;/-),'+*+%&%%)42)>:96*/4'8-2:>.:51&%$&/(1%:9*9/6'*%'-*2+.(++0'8,:08=.>&,1=@?>6''6)0%*.'(1):/2;7'7)1+*&,52>@.<=>)0)0792=;';)17>,>7:),*&*.%%%%#%$&"%*7':7)+-)9<;62'((''%%'%1$28**8%%#&$##$	AS:i:708	MD:Z:17G24C61A10^C7C1C0T43^GT34T7^G0G0G0T113G19^GG22^ATT18^C38T1^AAATGCTG17	NM:i:44	cm:i:32	de:f:0.0505	ms:i:735	nn:i:0	s1:i:228	s2:i:0	tp:A:P	MM:Z:C+h,2,17,12,4,0,2,22,1,10,6,0,0,7;C+m,2,17,12,4,0,2,22,1,10,6,0,0,7;	ML:B:C,0,0,0,0,0,0,0,0,0,0,0,0,0,254,254,255,254,255,255,255,255,255,255,110,254,248	qs:i:9	mx:i:3	ch:i:49	rn:i:118	st:Z:2023-07-06T12:28:29Z	f5:Z:FAV71569_pass_1c3972e3_f5114067_0.fast5	ns:i:5661	ts:i:45	sm:f:78.563	sd:f:10.0631	sv:Z:med_mad	RG:Z:f511406703c9d9eafbc59f28229b17deccce7224_unknown

I have then ran the pile up with -`-force-allow-implicit` and got the output. could you explain the cause for the ImplicitProbModified error?

do you also suggest setting `--sampling-frac 1.0` for adaptive sampling, and/or `--filter-threshold`?

**Comment by ArtRand** [comment]
Hello @cherlynty 

The reason for not allowing the mod-tags (without an override) like you have (C+m) is largely historical. The C+m-style is from before the `?` and `.` flags were introduced (see the [spec](https://samtools.github.io/hts-specs/SAMtags.pdf), page 7). The CpG models used by Nanopore always emit a probability of a base being modified or canonical so long as the base call sequence is CG. So interpreting a missing probability as "canonical" would be incorrect. The `?` flag is intended to communicate this situation, where a missing probability means missing information. We made the decision to have a guard around this in `modkit` partially to force conversion of the old tags (C+m) to the new tags (C+m?). 

The `--sampling-frac` option specifies what proportion of the reads to use in order to estimate the pass threshold. There is also a `--num-reads` option that does the same thing, I generally recommend using the `--num-reads` option, it's a little quicker. Unless you see in the logs that `modkit` is failing to sample very many reads, I think the default options are fine. If you're doing lots of runs or exploratory analysis, you can run `modkit sample-probs` and record the thresholds (and optionally more information with the `--hist` option), then pass these numbers to `pileup`. The procedure is the same, but it can save time. 

Hope this answers your question, don't hesitate to ask for more clarification.

**Comment by cherlynty** [comment]
Helllo @ArtRand,

thank you for the explanation. I am looking at all contexts of 5mC (CG, CHG and CHH). I am seeing a number of reads being skipped for no mod calls, and am wondering if the  `?` and `.` flags are overrepresented at the CHG and CHH contexts.
eg:
`Skipped: record cfcd8128-b867-42a3-8e82-9dfc010911e9 has no mod calls`

do you also have any advise on using modkit to call specifically only non-CpG contexts?

Thank you!

**Comment by ArtRand** [comment]
Hello @cherlynty , I apologize for the slow response. 

If you are trying to get 5mC in all-contexts, then I recommend using the "all-context" 5mC model (`dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mC@v2 (5 kHz)` [dorado docs](https://github.com/nanoporetech/dorado/#modified-base-models)). This model will make a 5mC methylation call at every cytosine in the read. The log line you're seeing is emitted when a read doesn't have any base modification calls (MM tag is empty). It may be worth inspecting a few of these reads to be sure that the MM/ML tags are indeed empty (no positions reported, the tag may still be there) and that the read sequence doesn't have any CG subsequences. 

If you want to get non-CpG contexts, I recommend running `modkit pileup` without the `--cpg` flag, just normal defaults 

```
modkit pileup <input.bam> <output.bed>
```

Then use `modkit motif-bed` to find the locations you want for example

```
modkit motif-bed <genome.fasta> CH 0
```

Finally a `bedtools` stranded intersection.

```
bedtools intersect -s -a <pileup.bed> -b <ch_motifs.bed> > pileup_ch.bed
```

Hope this helps. More than happy to answer any further questions.

**Comment by ArtRand** [comment]
@cherlynty In recent releases you can use `--motif CH 0` as well. Feel free to re-open this issue if you have additional questions or encounter any problems.
