### ISSUE TITLE
Error code:  Error! didn't sample enough data, try a larger fraction of another seed

### ISSUE THREAD

**Issue by kaufmanelij** [nanoporetech/modkit#4]
Hi!

I'm trying to get a bedMethyl file from some Nanopore modbam files that I generated with Guppy 6.4.6 using cfg: dna_r10.4.1_e8.2_400bps_modbases_5mc_cg_sup_prom.cfg. 

Originally I was running into errors when giving the folder that the files are in, or as the files with a wildcard, so I ended up using samtools merge to merge all of my modbams and then index. This merged modbam file is 125GB. Now my current error is as follows:

`modkit pileup 7254_wgs_meth_sorted.bam 7254_wgs_pileup.bed --log-filepath 7254_wgs_pileup.log --combine-mods`

from the log file:
`[src/logging.rs::54][2023-04-19 10:23:04][DEBUG] command line: modkit pileup 7254_wgs_meth_sorted.bam 7254_wgs_pileup.bed --log-filepath 7254_wgs_pileup.log --combine-mods
[src/commands.rs::100][2023-04-19 10:23:04][INFO] sampling 10042 reads from BAM
[src/interval_processor.rs::227][2023-04-19 10:23:04][INFO] sampled 0 probabilities
[src/bin/main.rs::15][2023-04-19 10:23:04][ERROR] Error! didn't sample enough data, try a larger fraction of another seed`

Any reason that it would be sampling 0 probabilities? I get an identical error when I try just a single indexed modbam file from the Guppy output, and no difference whether or not I include --combine-mods'

Thanks! Let me know if I am not using the tool correctly.

**Comment by faulk-lab** [comment]
Did you map the reads to a reference when basecalling with guppy?

**Comment by kaufmanelij** [comment]
I did not. Is there a way to map them now, or will I need to re-call them?

**Comment by faulk-lab** [comment]
Sure you can map them now. Since minimap2 doesn't accept bam as input you need to convert them to fastq format first, but retain the modifications `-T MM,ML` then pipe to minimap2 and sort and index and then retry `modkit`. The `-12` is for the number of cores you have. In my case it's 12.

`samtools fastq -T MM,ML <sample>.unmapped.modbam.bam | minimap2 -y -ax map-ont <reference>.fa - -t 12 | samtools view -u - | samtools sort -@ 12 -o <sample>.modmapped.bam; samtools index <sample>.modmapped.bam -@ 12`

**Comment by ArtRand** [comment]
Hello @kaufmanelij 

A couple things are going on here. As @faulk-lab mentioned `modkit pileup` requires alignments to a reference. Sounds like you've sorted that out (thanks @faulk-lab for the support). With an unaligned modBAM you can run `modkit summary` and get some stats on base modifications at the read level.

If you have a large modBAM, you can specify the `--region <chrom>` option so that you can shard the processing over multiple machines or quickly get an answer in order to iterate. I could imagine supporting lists of files in the future, but that's not currently supported, as you found out. I'll update the documentation. 

All that being said, the error you're getting isn't appropriate either. I'm planning on having a release of modkit this week (promoting 0.1.4-rc1) and I'll make sure this is addressed in that version. Thanks for the feedback!

**Comment by ArtRand** [comment]
Release [0.1.4](https://github.com/nanoporetech/modkit/releases/tag/v0.1.4) should partially adress this issue. With an unmapped modBAM `modkit` pileup will now estimate the threshold probability from your reads, but obviously it cannot actually perform the pileup. It's not a total waste of effort because you can use the estimated threshold directly once you do have the mappings. Let me know if this works for you.

**Comment by kaufmanelij** [comment]
@ArtRand I'm mapping it and will let you know how it looks when I've got that through pileup too, but the modkit summary was lightning fast.

input: 
`modkit summary 7254_wgs_meth_sorted.bam`

output:
`> sampling 10042 reads from BAM
> calculating threshold at 10% percentile
> calculated thresholds: C: 0.9824219
> this output format will not be default in the next version, the table output (set with --table) will become default and this format will require the --tsv option
mod_bases       C
count_reads_C   10042
C_calls_modified_m      280652
C_frac_modified_m       0.7129082078481579
C_filtered_modified_m   17709
C_calls_unmodified      113020
C_frac_unmodified       0.28709179215184216
C_filtered_unmodified   22276
C_total_mod_calls       393672
C_total_filtered_mod_calls      39985
total_reads_used        10042`

**Comment by ArtRand** [comment]
Great. Keep in mind that `modkit summary` is just a sample of the reads and that the base modification calls include unmapped calls.
