### ISSUE TITLE
unexpected behaviour from multiple modikit commands

### ISSUE THREAD

**Issue by owenwilkins** [nanoporetech/modkit#42]
Hello. I have been using modkit to process modification calls generated from dorado with the `dna_r10.4.1_e8.2_400bps_sup@v4.2.0` model, and obtained unexpected results from several commands. In many cases, the number of supporting reads I can see in the BAM file does not agree with the results I get from modkit commands. I was hoping someone may be able to clarify how modkit behaves in several scenarios. 

1. `sample-probs` only provides quality score percentile estimates for the canonical base in the `thresholds.tsv` file. From the documentation, I expected to see estimates for `m` and `h` also. I have copied the contents of the `threshold.tsv` file below. if I use the `--hist`` argument, the output does include `m` and `h` in the `probabilities.tsv` file, which is confusing. 

 base  percentile  threshold 
 C     10          0.8300781 
 C     50          0.98046875 
 C     90          0.9941406 

The command I run is 
`modkit sample-probs -t 20 mod_basecall_aligned.bam 
	--out-dir sample_probs-on-target --hist 
	--only-mapped --include-bed target-regions.bed
`
I use `include-bed` as this is from an adaptive sequencing run. 

2. I have been trying to calculate the probability threshold estimates myself for each modified base using the output of `extract` however in the output, there appear to be reads missing for some modification calls that I can see in the BAM file via IGV. perhaps someone could clarify exactly how the probability thresholds could be calculated using the output from `extract`. this would also be helpful as I would like to visualize the distribution of probabilities for a given modification. my command is: 
`
modkit extract mod_basecall_aligned.bam base-mod-data.tsv \
	--include-bed target-regions.bed \
	--mapped \
	-t 20
`

3. using `pileup` with the `combine-strands` arguments appears to include reads in the output file that have been combined those from the + strand, however none from the negative strand. when i count the values in the 6th column of the output I get the output below: 
           .      + 
144134 713884 

I am confused as to why no - strand only entires exist, as I can see these in the BAM file. Additionally, there are sites where I can see + and - strand aligned reads, however there is only an output for the + strand at that site in the output file. Perhaps someone could advise why this might be happening. My code:
`modkit pileup mod_basecall_aligned.bam mod_basecall_aligned.bed \
	--cpg \
	--threads 40 \
	--ref $ref_dir/Homo_sapiens.GRCh38.dna.primary_assembly.fa \
	--include-bed target-regions.bed \
    --combine-strands  `

Thanks in advance,

**Comment by ArtRand** [comment]
Hello @owenwilkins, I'm going to try and address your questions one at a time. 

> 1. sample-probs only provides quality score percentile estimates for the canonical base in the thresholds.tsv file. From the documentation, I expected to see estimates for m and h also. I have copied the contents of the threshold.tsv file below. if I use the --hist`` argument, the output does include mandhin theprobabilities.tsv` file, which is confusing.

This is the intended behavior, `modkit sample-probs` will tell you the estimated pass threshold for each modified _canonical_ base at various percentiles. So the output you see in `thresholds.tsv` are the estimated pass thresholds for cytosine modifications (any of them) when dropping the lowest 10%, 50% and 90% confident calls. 

None of the `modkit` sub-commands will attempt to estimate a threshold per-modification (i.e. one for 5mC and one for 5hmC). That is what the `--hist` output is indented for, as you've discovered.

> 2. I have been trying to calculate the probability threshold estimates myself for each modified base using the output of extract however in the output, there appear to be reads missing for some modification calls that I can see in the BAM file via IGV. perhaps someone could clarify exactly how the probability thresholds could be calculated using the output from extract. this would also be helpful as I would like to visualize the distribution of probabilities for a given modification. my command is:
modkit extract mod_basecall_aligned.bam base-mod-data.tsv \ --include-bed target-regions.bed \ --mapped \ -t 20

The output from `extract` will only report on primary alignments (we may remove this limitation in the future). On the other hand IGV will show secondary and supplementary alignments with base modification calls. Could you check if the reads that are missing from the `extract` output are non-primary in your IGV session? If this isn't it, could you send me a small BAM from which `modkit extract` is missing calls as well as the IGV screen shot with the base modification calls present?

> 3. using pileup with the combine-strands arguments appears to include reads in the output file that have been combined those from the + strand, however none from the negative strand. when i count the values in the 6th column of the output I get the output below:
. +
144134 713884

As per the [subcommand documentation](https://nanoporetech.github.io/modkit/advanced_usage.html#pileup):

> When performing CpG analysis, sum the counts from the positive and negative strands the counts for the positive strand.

And noted in the [usage documentation](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#narrowing-output-to-cpg-dinucleotides):

>The strand field of the output will be marked as '.' indicating that the strand information has been lost.

The `.` indicates that the `+` and `-` strands have been summed. If you see `+` that means there was no `-` strand summand. If you see `-` strand base modification calls in IGV, it's likely that the base modification calls did not pass the threshold confidence value. We discussed internally, and agreed this is confusing, however, so I'll be sure to change this behavior in the next release. You should not see `-` strands because all of those counts will be moved to the `+` strand position, even if the `+` strand count is 0, increasing the potential for confusion and why it will be changed. 

Please let me know if this helps.

**Comment by owenwilkins** [comment]
thanks very much, I appreciate the rapid response. that definitely clears up question 1, although I still seem to be seeing discordance between the number of reads output by `pileup` and `extract` compared to IGV. I went and filtered my BAM to keep only primary alignments so that doesn't seem to be the issue. 

the issue seems to be around how read strand is taken into account, so perhaps I am just missing something obvious.. below is an example of a region where I see bases with good Phred scores mapped to the + and - strands, but pileup gives the output included below the figure, with 11 bases contributing to the call (1 failed to pass call threshold), which makes sense if I count the read number aligning to the +ve strand which is 12, but all the minus strand calls seem to be ignored for some reason. 

![coverage-example](https://github.com/nanoporetech/modkit/assets/17816328/cb3219c5-81de-4886-bbeb-382cd4549375)

   V1       V2       V3 V4 V5 V6       V7       V8      V9                      V10
1: 10 70274434 70274435  h 11  + 70274434 70274435 255,0,0   11 0.00 0 0 11 0 1 0 0
2: 10 70274434 70274435  m 11  + 70274434 70274435 255,0,0 11 100.00 11 0 0 0 1 0 0

`extract` also only outputs 12 reads for this call, all of which are on the + strand. 

happy to share a small BAM if the answer to this isn't obvious. what would be the best way to do that? 

sorry again if I'm just missing something

**Comment by ArtRand** [comment]
Hello @owenwilkins,

If it's possible to select just the reads in this small region with samtools view and attach it to this thread I'd be happy to take a look.

**Comment by owenwilkins** [comment]
Great thanks. Small sam attached. 

Reference for the alignments was the GRCh38 primary_assembly from Ensembl 97: https://ftp.ensembl.org/pub/release-110/fasta/homo_sapiens/dna/

[small.bam.txt](https://github.com/nanoporetech/modkit/files/12323687/small.bam.txt)

**Comment by owenwilkins** [comment]
sorry, forgot to give you the command and log file. 

modkit pileup mod_basecall_aligned.bam mod_basecall_aligned.bed \
	--cpg \
	--threads 40 \
	--ref $ref_dir/Homo_sapiens.GRCh38.dna.primary_assembly.fa \
	--include-bed target-regions.bed \
        --log-filepath log.txt
        --combine-strands  

[log.txt](https://github.com/nanoporetech/modkit/files/12324401/log.txt)

**Comment by ArtRand** [comment]
@owenwilkins could you check what character is in the "strand" column of `target-regions.bed` (the sixth column)? For pileup to work with `--combine-strands` the intervals in `target-regions.bed` will need to completely overlap the CpG dinucleotides and have strand `.` or have both the `+` position and the `-` position. I went through the BAM you sent and the numbers I'm getting correspond to what I see in IGV, but I'm not using the `--include-bed` option. If you're trying to get a general region instead of specific CpGs you could use the `--region` option instead.

**Comment by owenwilkins** [comment]
I have +/- values being in the sixth column of the BED thats being passed to `target-regions.bed`, which perhaps is the issue as only reads on the same strand as the feature are being counted by pileup. I'll try changing the 6th column to a '.'s and hopefully this will allows read from both strands to be counted. will let you know if it works. thanks again!

**Comment by ArtRand** [comment]
For `--combine-strands` you'll need to have the `+` strand interval overlapping the `C` and the `-` strand overlapping the reverse strand `G`, or `.` strand for the entire interval. You can use `modkit motif-bed <fasta> CG 0` to see an example of what I mean.

**Comment by owenwilkins** [comment]
ok great thanks. I changed to `.` for the entire interval and am now getting the expected number of reads in the output of `pileup` based on what i see in IGV. thanks again.

**Comment by ArtRand** [comment]
No problem, happy to help.

**Comment by ArtRand** [comment]
@owenwilkins feel free to re-open this issue if you encounter any more related problems.
