### ISSUE TITLE
Q: `--filter-threshold FRAC` description

### ISSUE THREAD

**Issue by sklages** [nanoporetech/modkit#6]
I do understand what `--filter-percentile` is actually doing. 

I am not sure though what `--filter-threshold` is really doing, nor what it (potentially) changes in the results file.
Technically it sets a "threshold", okay. 

Can you elaborate a bit on that parameter, describing what it is actually doing, what kind of threshold is set and how this influences the results in the results file(s)? Or if this parameter should be better left untouched in order to let `modkit` set the threshold?

This is a **very basic** question and the explanation will probably be quite simple, but somehow I didn't get it yet :-)

**Comment by ArtRand** [comment]
Hello @sklages,

The `--filter-threshold` allows you to set a minimum probability for base modification calls. For example, if you set this number to 0.75, then base modifications with probability < 0.75 will be considered "fail". In the case of `modkit pileup` failed calls are not added to the `score` (columns 5 and 10, see the [readme](https://github.com/nanoporetech/modkit#bedmethyl-column-descriptions)), but _will_ be added to the N_filtered (column 16). 

This option exists to override the on-the-fly estimation of the threshold. For example, say your workflow produces an unsorted modBAM, so could run `modkit sample-probs` on >= 10,000 reads, get the threshold from there. Then you can skip the on-the-fly step in subsequent operations (`summary` and `pileup`). 

In general, we recommend that you let `modkit` estimate the threshold for you, on the fly, because different samples and different models will probably have slightly different values. Don't hesitate to ask if this still isn't clear.

**Comment by sklages** [comment]
@ArtRand - thank you very much for your comprehensive explanation. Got it now :-)
