### ISSUE TITLE
`modkit dmr multi` has incorrect output, and fails to do pairwise comparison 

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/modkit#74]
In my instance of running `modkit dmr multi` I get a lot of failed regions. However the output of the command shows contradicting information on the number of regions which failed. See below.

```
modkit dmr multi -s methylation/*/top.bed.gz top -s methylation/*/middle.bed.gz middle -s methylation/*/bottom.bed.gz bottom -i methylation/*/top.bed.gz.tbi top -i methylation/*/middle.bed.gz.tbi middle -i methylation/*/bottom.bed.gz.tbi bottom -r gene-coordinates.txt -o methylation/modkit_dmr_out -t 10 --ref mags/*.fna --base C --base A
> loading user-specified index at methylation/Polaribacter_r-contigs/top.bed.gz.tbi
> loading user-specified index at methylation/Polaribacter_r-contigs/middle.bed.gz.tbi
> loading user-specified index at methylation/Polaribacter_r-contigs/bottom.bed.gz.tbi
> loaded 4917900 regions
> processing 15 regions concurrently
[00:00:00] ##############--------------------------       1/3                                                                                                 > loading user-specified index at methylation/Polaribacter_r-contigs/top.bed.gz.tbi
> loading user-specified index at methylation/Polaribacter_r-contigs/middle.bed.gz.tbi
[00:00:13] ###########################-------------       2/3       comparing top and bottom
[00:00:00] ----------------------------------------       0/4917900 regions processed
> 0 regions failed to process                                                                                                                                 [00:00:13] ###########################-------------       2/3       comparing top and bottom                                                                  > loading user-specified index at methylation/Polaribacter_r-contigs/middle.bed.gz.tbi
> loading user-specified index at methylation/Polaribacter_r-contigs/bottom.bed.gz.tbi
middle_bottom.bed  top_bottom.bed  top_middle.bed
```

As you can see it says 0 regions failed to process, where as the reality is every region failed to process. In addition the final output is odd and shows partially complete progress bars, and incomplete lists (ends at `2/3`). 

Moreover it is very unclear why the regions failed to process (e.g. did the ROI not exist in both files?). 

Finally, it seems like the software did not do a comparison between every sample provided.

**Comment by ArtRand** [comment]
Hello @Ge0rges,

Could you attach the log file (run with `--log-filepath`)?

**Comment by Ge0rges** [comment]
While getting the log file I ran into another `> Error! No such file or directory (os error 2)`. It would be very useful if the `modkit` could specify which path it failed to find.

[Here](https://www.dropbox.com/scl/fi/r4owtu69eqjhj3el7mah0/dmrs.log?rlkey=10vt5aevj66myrvnscn41bumr&dl=0) is the log file. Thank you for your help. Here is the command that generate the inputs, please ignore the variable names as these were pulled from a script.

```
        modkit pileup $bam methylation/$genome_name/$bam_name.bed -t $num_threads --only-tabs

        bgzip -k --threads $num_threads methylation/$genome_name/$bam_name.bed
        tabix methylation/$genome_name/$bam_name.bed.gz
```

**Comment by ArtRand** [comment]
@Ge0rges great, I'll take a look - I'll also fix the logging issue.

**Comment by ArtRand** [comment]
@Ge0rges 

A couple of things going on here. First of all, the logging is missing a variable, making it hard to understand. I'm working hard to get an update out very soon and I'll make sure this logging is improved. Sorry about that. 

Thanks for the log file, I have an idea of where the problem is. Is it possible that the regions file (`methylation/Polaribacter_r-contigs/gene-coordinates.txt`) has different contig names than the bedMethyl files? For example, `contig_1:206-683` in the regions file is `contig_1` in the bedMethyl? The contigs in the bedMethyl and the regions need to be the same or the region will be marked as "failed". 

Moving to the next point, the progress bars are getting mangled, so the "0 regions failed to process" is stale information. I'll get this fixed too. 

The `modkit dmr multi` command essentially runs `modkit dmr pair` in a loop. You could try running just one comparison by itself for example: 
`top.bed.gz` vs `middle.bed.gz`

```
modkit dmr pair \
 -a top.bed.gz \
 -b middle.bed.gz \
 -r methylation/Polaribacter_r-contigs/gene-coordinates.txt \ # make sure these contigs overlap
 --ref mags/Polaribacter_r-contigs.fna \
 --base C --base A --log-filepath dmrs.log # etc.
```

Thanks for bringing this up I'll aim to get the user experience improved in the next release.

**Comment by Ge0rges** [comment]
When I modified the regions of interest bed to fix the contig names, I get similar errors in the log file. Moreover, I get a lot of these errors:

```
  left: `2`,
 right: `1`', src/dmr/pairwise.rs:68:13
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', src/dmr/pairwise.rs:68:13
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', src/dmr/pairwise.rs:68:13
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', src/dmr/pairwise.rs:68:13
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
```

I made available the BED file generated by pileup, the tbi, and the regions of interest file [here](https://www.dropbox.com/scl/fo/qscuadhscmqfbfioj9su0/h?rlkey=ne47ycfzkf2io0txjpkgo2r5j&dl=0). Thanks for your help.

**Comment by ArtRand** [comment]
Hello @Ge0rges,

The assertion error is happening because you have positions in the bedMethyl like this:
```
contig_70       673     674     a       2       -       673     674     255,0,0 2       0.00    0       2       0       0       0       1       0
contig_70       673     674     h       1       -       673     674     255,0,0 1       0.00    0       1       0       0       0       2       0
contig_70       673     674     m       1       -       673     674     255,0,0 1       0.00    0       1       0       0       0       2       0
```
where there are cytosine calls _and_ adenine calls. Obviously, this is a sequencing artifact. Likely the adenine is the correct base since there are 2 reads with A-mods and only 1 with a C-mod, but I don't know since I don't have the reference. The assertion error is firing because the algorithm in modkit checks that the reads reporting on a reference sequence position are all reporting for the same primary sequence base. It does this by asserting that the set of "scores" is cardinality 1. Long story short, in the short term, if you use a modBAM with modification calls on more than 1 base you'll have to perform some data cleaning before running `modkit dmr`. Checking that only reads reporting on a primary base isn't a strict requirement of the model. I can give you a build without this check and requirement if you'd be willing to test it.

**Comment by Ge0rges** [comment]
I am willing to test it if that's useful to you. But my understand was that the program would pick the correct modification type based on the reference sequence (i.e. which base is actually at that location) and confidence scores, how come that isn't the case?

I don't believe I see those errors.

**Comment by Ge0rges** [comment]
Great! I don't see anything that isn't in that log file. I haven't rerun it with filtering those out yet.

**Comment by ArtRand** [comment]
@Ge0rges ,

Alright here is a build with that specific check disabled. It will still log when this happens, so expect to see that. I also tidied up the other log message to make it more clear. Needless to say, this build is experimental. 
[Uploading modkit_v0.2.2-dev54ea39e.zip…]()

**Comment by Ge0rges** [comment]
I'm encountering an issue where the tabix header doesn't contain the name of the contig for some reason. Any hints here? The tabix header is created directly from the BAM I'm passing. When I look at the bed and the ROI file I'm giving, the contig names seem identical. The files are in that dropbox folder.

**Comment by ArtRand** [comment]
Hello @Ge0rges,

I used the `top.bed.gz.tbi` file you have put in the dropbox folder. What I found:
There are 19 references in the tabix header, they are:
contig_226_partial_0_323472
contig_229
contig_232
contig_273
contig_430
contig_440
contig_5
contig_550
contig_559
contig_572
contig_603
contig_656_partial_20600_312265
contig_67
contig_68385
contig_70
contig_717
contig_72
contig_73
contig_74


There are 57249 contig names in gene-coordinates.txt.
There are 2 contigs in the tabix header not in gene-coordinates.txt they are:
contig_226_partial_0_323472
contig_656_partial_20600_312265

There are 57232 contigs in the gene coordinates not in the tabix header, I've attached that list to this thread. 

This explains why you are seeing so many lines in the log complaining that the chrom id for a contig cannot be found in the tabix header. I imagine for your experiment, there will be contigs that are present in a given pair of samples for not for another pair. So the gene-coordinates.txt will be a super set of the contigs in a given bedMethyl. However, you may consider removing entries from gene-coordinates.txt that aren't in any of the samples (this will always fail). I'm hesitant to remove or silence this log since it is informative of a potential user error, even though it can be noisy. 

[missing_in_tabix.txt](https://github.com/nanoporetech/modkit/files/13230302/missing_in_tabix.txt)
[tabix-check.zip](https://github.com/nanoporetech/modkit/files/13230305/tabix-check.zip)

**Comment by Ge0rges** [comment]
Ah I see. I made the gene-coordinates.txt to be every possible entry so that makes sense. However, none of my reads get processed at all it seems.

**Comment by ArtRand** [comment]
That's strange. A quick `bedtools intersect` shows that there are 17 contigs in the gene-coordinates.txt that have an entry in `top.bed`. Maybe send over a log and the command you ran?

**Comment by ArtRand** [comment]
@Ge0rges The latest release will automatically select the correct bedMethyl records to use for a position (i.e. 5mC for cytosines and 6mA for adenines). I would highly recommend using it in favor of the build I provided earlier. There are also some logging fixes that should make the program easier to use.

**Comment by Ge0rges** [comment]
This latest build solved my problems I believe! Or at least, the output is easier to understand and I'm not confused. Thank you for all your help. I will close those but have two questions.

Is there a flag to filter the output score by statistical significance?
Is there a way to get the DMR output such that each modified nucleotide is a row, instead of getting total counts in a region?

**Comment by ArtRand** [comment]
@Ge0rges 
@Ge0rges 

> Is there a flag to filter the output score by statistical significance?

No. The scoring is described in the [documentation](https://nanoporetech.github.io/modkit/intro_dmr.html#scoring-details). The counts for each modification are reported in columns 6-9, so you could parse these and run the statistical test of your choice.

> Is there a way to get the DMR output such that each modified nucleotide is a row, instead of getting total counts in a region?

I think what you want here is the bedMethyl?

**Comment by Ge0rges** [comment]
Yes that's one way to think of it, the DMRs output as bedmethyl. Is that a flag I missed?

**Comment by ArtRand** [comment]
Oh, I see what you mean. To get position-level information for the DMRs, I would
```
bedtools intersect -a <original_bedmethyl> -b <DMR_output> -wb > bedmethyl_with_dmr_annot.bed
```

**Comment by Ge0rges** [comment]
But that assumes every methylated nucleotide in  that region is DMRed correct?

**Comment by ArtRand** [comment]
@Ge0rges I apologize for the slow reply. 

Are you trying to find differentially methylated cytosines/adenines or are you interested in finding differentially methylated regions? It's fine if the answer is "both". 

With what you're currently doing, using regions of interest (a.k.a gene coordinates), what you could do is first find the differentially methylated regions as we've been discussing. Then subset the bedMethyl with `bedtools` as I [mentioned](https://github.com/nanoporetech/modkit/issues/74#issuecomment-1799536230). 

Once you have the subsetted bedMethyl, you're correct that not every base in that region will be differentially methylated (plus, this will only give you the records from one sample). So what you could do is join the two subsetted bedMethyl files together and find positions that have different methylation levels, for example with a statistical test as you've alluded to. 

I'm going to add functionality to easily and directly find differentially methylated _bases_ in the next release. This function will compare each position in a pair of samples and score them. You could imagine doing something in two steps where you find the DMRs as you've done, then drill down to differentially methylated positions within those regions.

**Comment by Ge0rges** [comment]
Indeed, both. Sounds like what I need is already being planned for however which is great! `modkit` is quickly becoming a more useful alternative to Methylkit. Thanks for all the help!

**Comment by ArtRand** [comment]
More than happy to help. The DMR functionality is the newest feature in `modkit` so I'm glad you're using it and providing feedback. Thanks for helping improve the software!
