### ISSUE TITLE
Zero reads recognized in megalodon basecalled .bam file

### ISSUE THREAD

**Issue by OberonDixon** [nanoporetech/modkit#82]
I am trying to analyze some .bam files that came out of the older megalodon basecalling pipeline. At first I was getting a message suggesting that all of the reads were being ignored.

I am simply running
`modkit pileup bam_input_path bed_output_path`

And I got this:

> calculated chunk size: 6, interval size 100000, processing 600000 positions concurrently
> attempting to sample 10042 reads
> Error! not enough data points (got 0) to calculate percentile

Then I saw that this older .bam file used Mm and Ml rather than MM and ML in the bam tags:
```
megalo_bamfile = pysam.AlignmentFile(two_color_r9,'rb')

next(megalo_bamfile)

next(megalo_bamfile)

next(megalo_bamfile)

first_read_megalo = next(megalo_bamfile)

for tag,value in first_read_megalo.get_tags():

    print(tag,value)
```

> RG 1
> Mm A+Y,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;C+Z,0,0,0,0,0,0,0,0,0,0,0,0,0;
> Ml array('B', [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 8, 0, 0, 0, 16, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 170, 0, 0, 0, 2, 2, 0])

I ran modkit update-tags successfully and it seems that the MM and ML tags are labelled correctly now, but it still isn't working - I now don't even get the message saying it is sampling reads.

> RG 1
> MM C+Z,0,0,0,0,0,0,0,0,0,0,0,0,0;A+Y,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;
> ML array('B', [0, 1, 0, 0, 0, 0, 170, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 8, 0, 0, 0, 16, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

> calculated chunk size: 6, interval size 100000, processing 600000 positions concurrently
> Done, processed 0 rows. Processed ~0 reads and skipped zero reads.

One thought I had is that perhaps the base modification labels (C+Z and A+Y, as compared to C+m and A+a) are causing the issue. Does that sound right, and if so, is there a tool to adjust these? Otherwise, what else might be wrong with the .bam file? I have some of my own pileup generating tools that work 100% fine on this .bam file so I know the contents are good.

Another thing I was wondering was whether the update-tags operation has harmed my .bai index file's ability to index the .bam file. I just used the same index but could also try re-indexing. However, this seems unlikely to me because pysam is working just fine and if I recall correctly it also relies on a working .bam.bai file; I can pull up reads one by one no problem and they still have their contents intact in the retagged version.

**Comment by ArtRand** [comment]
Hello @OberonDixon,

You may need to add `--force-allow-implicit` to the `modkit pileup` command, eg:

```bash

modkit pileup {bam_input_path} {bed_output_path} \
  --force-allow-implicit \
  --log-filepath {pileup_log_filepath}
```

I'd recommend using the `--log-filepath` option and inspecting the contents in cases like this as mentioned in the [troubleshooting docs](https://nanoporetech.github.io/modkit/troubleshooting.html#no-rows-in-modkit-pileup-output). 

If you're using the latest version of modkit ([0.2.2](https://github.com/nanoporetech/modkit/releases/tag/v0.2.2)), you should be able to use `Z` to mean 5mC and `Y` to mean 6mA, older versions will not let you, however. I'd recommend changing the codes to be specification-compliant like so:

you can test this out with a file named `bc_anchored_10_reads_old_tags.bam` in the [test data directory](https://github.com/nanoporetech/modkit/tree/master/tests/resources)

```bash 

# use this mode if it's an all-context model
mode=implicit

# use this mode if it's a CG model
#mode=ambiguous


modkit update-tags {bam_input_path} - --mode ${mode} \
  | modkit adjust-mods - - --convert Z m --convert Y a \
  | samtools sort - -O BAM -o {adjusted_updated_bam_output_path}

```

If you're using an "all-context" model (i.e. the base modifications are called at all cytosines and adenines) you can use the `implicit` mode, for the CG model use the `ambiguous` mode.

The above should work with older versions of `modkit` as well. The modBAM you get after the `update-tags` and `adjust-mods` commands should be suitable for `pileup`. I would re-index the modBAM since these steps will remove supplementary and secondary alignments. Let me know if you have any additional questions.

**Comment by Yijun-Tian** [comment]
For megalodon base call files, interesting to find that --force-allow-implicit will make pileup to work correctly and had to use --ignore-implicit to make extract to successfully call on CpG sites.

**Comment by OberonDixon** [comment]
I had to put this on hold for a good while to finish up some other projects, but came back to it today and I was able to resolve the above issue and get everything running as desired. Here's what I did, all running modkit v0.2.2. My megalodon basecalled .bam file was already sorted and indexed, and it seemed to stay sorted through the operations because I was able to just re-index at the end without re-sorting. This re-indexing with samtools was necessary because otherwise modkit pileup throws and error saying it needs an index.

```
modkit update-tags megalodon_all_context_bam_input.sorted.bam output.sorted.bam --mode implicit
modkit adjust-mods output.sorted.bam output.ma.sorted.bam --convert Z m --convert Y a
samtools index output.ma.sorted.bam
modkit pileup output.ma.sorted.bam
```
Running `update-tags` got pileup running without errors, but not actually processing any rows. I could run `modkit extract` after this, which showed that the Y and Z mod labels were in place. By also using `adjust-mods`, `modkit pileup` gave me what I wanted/expected, processing all the specified regions and capturing the different base modification motifs I was looking for.

Thanks a ton for the help and support, I can now move forward with the next phase of this project!!
