### ISSUE TITLE
`dmr` with coverage threshold

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/modkit#83]
I was wondering if it's possible to filter `dmr` results with a minimum coverage for any given modification. i.e. it has to be seen in X% of reads etc.? I'm trying how to understand how to apply the min coverage and q value filters offered by `methylkit` using the score produced by `dmr`.

**Comment by Ge0rges** [comment]
Great! Thank you for this thorough answer. I'm definitely interested in moving away from `methylkit` which has been behind the many questions.

**Comment by ArtRand** [comment]
Just curious, what functionality are you using in methylkit that's not available in modkit? I imagine a lot of people will have experience with BS-Seq packages, and I'd like to make the transition as easy as possible.

**Comment by Ge0rges** [comment]
I would say the main thing that `methylkit` does which `modkit` lacks and is in scope for it, is `dmr` across multiple samples rather than just pairwise comparison. So the calculation of the mean methylation patterns across samples, and the `dmr` between each sample and that baseline.

**Comment by Ge0rges** [comment]
@ArtRand I think I didn't get what you meant by 

>  I think you could use a valid coverage filter for min coverage

as I don't see a flag for that. Did you mean simply filtering the input bam file for reads that have a certain coverage only? I was wondering if I would end up losing some data, versus looking at coverage only at methylated positions, but maybe I haven't wrapped my head around this well.

**Comment by ArtRand** [comment]
@Ge0rges sorry for the slow response,

If I recall correctly, I was suggesting that you can use the `N_valid_coverage` column in the bedMethyl for any filtering on coverage (i.e. number of reads reporting methylation status at a site). There is no flag for this, so you'll have to do it on the files yourself ahead of `modkit dmr` or MethylKit analysis. I'm going to make this an command line option in the next version for `dmr` along with support for testing individual bases instead of regions. 

Release would normally be this week, but it's a holiday week in the US - so probably early next week.

**Comment by Ge0rges** [comment]
Not slow! Thank you for there reply. Happy thanksgiving!
