### ISSUE TITLE
Question about mod_qual value in modkit extract

### ISSUE THREAD

**Issue by liliaevgeniou** [nanoporetech/modkit#95]
Hi, Thank you for making this software.

I just have a question about where you calculate "mod_qual" value in the "modkit extract" output table. I am guessing it is something to do with the ML flag in the BAM file (which is a probability out of 255), but when I calculate this, it does not exactly correspond to the value in "mod_qual". Moreover, for values which are 0 in the ML flag, it gives a non-zero number (like 0.0019). 

Would you please be able to give some guidance as to how this is calculated? Thank you very much!

**Comment by ArtRand** [comment]
Hello @liliaevgeniou,

The `mod_qual` values (which I will be renaming to `mod_probability` in the next minor version bump) are derived from the ML tags as you guessed. However, since the actual probabilities of the model must be discretized into a bin (0-255), when decoding the ML tag `modkit` centers the probability within the bin. That's why you never get 0 (and will never get 1.0). The calculation used in `modkit` is:

```rust
// qual is the value in ML tag, this function returns the value you get in `modkit extract`
fn qual_to_prob(qual: u16) -> f32 {
    let q = qual as f32;
    (q + 0.5f32) / 256f32
}
```

**Comment by liliaevgeniou** [comment]
Ah great, thank you so much!
